rails_home_link: "https://www.railstutorial.org/"
rails_help_link: "https://www.railstutorial.org/help"
rails_book_link: "https://www.railstutorial.org/book"
rails_contact_link: "https://www.railstutorial.org/contact"
rails_about_link: "https://www.railstutorial.org/about"
rails_author_link: "https://www.michaelhartl.com/"
rails_news_link: "https://news.railstutorial.org/"
rails_logo_link: "rails.svg"
ruby_on_rails_link: "https://rubyonrails.org/"
