rails_home_link: "https://www.railstutorial.org/"
rails_help_link: "https://www.railstutorial.org/help"
rails_book_link: "https://www.railstutorial.org/book"
rails_contact_link: "https://www.railstutorial.org/contact"
rails_about_link: "https://www.railstutorial.org/about"
rails_author_link: "https://www.michaelhartl.com/"
rails_news_link: "https://news.railstutorial.org/"
rails_logo_link: "rails.svg"
ruby_on_rails_link: "https://rubyonrails.org/"
name:
  length:
    minimum: 6
    maximum: 50
email:
  length:
    minimum: 10
    maximum: 50
  valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
password:
  length:
    minimum: 6
    maximum: 20
